# https://github.com/aws/karpenter-provider-aws/blob/main/examples/v1/br-custom-userdata.yaml
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: bottlerocket
  annotations:
    kubernetes.io/description: "EC2NodeClass for running Bottlerocket nodes with custom user data"
spec:
  role: "KarpenterNodeRole-${CLUSTER_NAME}" # replace with your cluster name
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${CLUSTER_NAME}" # replace with your cluster name
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${CLUSTER_NAME}" # replace with your cluster name
  amiSelectorTerms:
    - alias: bottlerocket@latest # Bottlerocket
  userData:  |
    [settings.kubernetes]
    kube-api-qps = 30
