{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-backend
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      service-type: backend
  namespaceSelector:
  matchNames:
  - {{ .Release.Namespace | quote }}
  endpoints:
  - port: http
  path: '/actuator/prometheus'
  interval: {{ .Values.metrics.interval }}
  scrapeTimeout: {{ .Values.metrics.scrapeTimeout }}
  targetLabels:
  - app.kubernetes.io/name
  timestamp: '{{ dateInZone "2006-01-02T15:04:05.000Z" (now) "UTC" }}'
{{- end }}