apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap
  labels:
    app: test-configmap
    appVersion: {{ .Chart.AppVersion | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  version: {{ .Chart.Version }}
  appVersion: {{ .Chart.AppVersion }}
data:
  my.value: "test"
