apiVersion: v2
name: chart
description: capabilities.apiVersions cannot be unset
issueLink: https://github.com/helm-unittest/helm-unittest/issues/300
supportedLinks:
- https://github.com/helm-unittest/helm-unittest/issues/300
- https://gitlab.com/gitlab-org/charts/gitlab-runner
todo:
- issue with subhcarts
type: application
version: 0.1.0
appVersion: "1.0.1"
# https://helm.sh/docs/helm/helm_dependency/
dependencies:
  - name: with-sub-chart
    version: 1.2.1
    # repository: file://charts/sub-chart
  - name: postgresql
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 0.8.3
    condition: postgresql.enabled
