apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: first-cronjob
  name: first-cronjob
  namespace: apps
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      activeDeadlineSeconds: 300
      template:
        metadata:
          annotations:
            ad.datadoghq.com/hello-world-new-resources.logs: '[{"team": "base","source": "cronjob","service": "cronjob"}]'
            ad.datadoghq.com/test-init-container: '[{"team": "base","source": "cronjob","service": "cronjob"}]'
          labels:
            app.kubernetes.io/managed-by: helm
            app.kubernetes.io/name: cronjob-base
            features.k8s.systems/pod-security: "true"
            features.k8s.systems/rw-volumes: "false"
            tags.datadoghq.com/service: cronjob-base
        spec:
          containers:
            - args:
                - arg1
                - arg2
                - arg3
              command:
                - curl
                - testing
              env:
                - name: DD_AGENT_HOST
                  valueFrom:
                    fieldRef:
                      fieldPath: status.hostIP
                - name: DD_APM_PORT
                  value: "8126"
                - name: DD_STATSD_PORT
                  value: "8125"
                - name: POD_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.podIP
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: DD_SERVICE
                  value: cronjob-test-hello-world-new-resources
                - name: DD_SERVICE_NAME
                  value: cronjob-test-hello-world-new-resources
                - name: DD_ENV
                  value: sandbox
                - name: DD_VERSION
                  value: 0.2.0
              image: curlimages/curl:latest
              name: first-cronjob-container
              resources:
                limits:
                  cpu: 50m
                  ephemeral-storage: 512Mi
                  memory: 128Mi
                requests:
                  cpu: 50m
                  ephemeral-storage: 512Mi
                  memory: 128Mi
              securityContext: {}
          restartPolicy: OnFailure
          tolerations:
            - effect: NoSchedule
              key: apm
              operator: Equal
              value: enabled
            - effect: NoExecute
              key: apm
              operator: Equal
              value: enabled
    schedule: '*/5 * * * *'
    successfulJobsHistoryLimit: 3
---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: second-cronjob
  name: second-cronjob
  namespace: apps
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      activeDeadlineSeconds: 300
      template:
        metadata:
          labels:
            app.kubernetes.io/managed-by: helm
            app.kubernetes.io/name: cronjob-base
            features.k8s.systems/pod-security: "true"
            features.k8s.systems/rw-volumes: "false"
        spec:
          containers:
            - args:
                - arg1
                - arg2
                - arg3
              command:
                - curl
                - testing
              env:
                - name: DD_AGENT_HOST
                  valueFrom:
                    fieldRef:
                      fieldPath: status.hostIP
                - name: DD_APM_PORT
                  value: "8126"
                - name: DD_STATSD_PORT
                  value: "8125"
                - name: POD_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.podIP
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              image: curlimages/curl:latest
              name: second-cronjob-container
    schedule: '*/5 * * * *'
    successfulJobsHistoryLimit: 3
