{{- range $name, $_ := .Values.machineTemplates }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: NutanixMachineTemplate
metadata:
  name: {{ $.Values.name }}-mt-{{ $name }}
spec:
  something: "true"
  # omitted for brevity..
{{- end }}